name: 'build'

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t bookdown - < .github/Dockerfile

    - name: Build site
      run: docker run --rm -v $(pwd):/src -e LANG=en-GB bookdown Rscript -e "rmarkdown::render('index.Rmd', 'distill::distill_article')"
