name: 'build'

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t bookdown - < .github/Dockerfile

    - name: Build site
      run: docker run --rm -v /$(pwd)://src -e LANG=en-GB bookdown

    - name: Publish site to gh-pages
      if: github.event_name != 'pull_request'
      run: |
        mkdir -p public
        cd public
        cp ../index.html ./
        touch .nojekyll
        git init
        cp ../.git/config ./.git/config
        git checkout --orphan gh-pages
        git add .
        git config --local user.email "push@gha"
        git config --local user.name "GHA"
        git commit -a -m "update ${{ github.sha }}"
        git push -u origin +gh-pages
